BUCKET_NAME = "shopify-summer21-uploads-bucket"
DDB_TABLE_NAME = "shopify-summer21-ddb"
HOST = "search-shopify-summer21-es-rjkbyddncxvclp3wbo6ya7bpou.us-west-1.es.amazonaws.com"
INDEX = "images"
URL = "https://" + HOST + "/" + INDEX + "/_doc"
API_ENDPOINT = "https://te10ynt1ma.execute-api.us-west-1.amazonaws.com/prod"